### ISSUE TITLE
Ver Datos (usuario)

### ISSUE THREAD

**Issue by mcolombo87** [Atixx/PlanCarrera#12]
Diseñar y desplegar los datos del usuario en pantalla y brindar la posibilidad de editarlo.

**Comment by Atixx** [comment]
@IrioneAraceli Fijate en el ultimo commit que esta todo funcionando, menos la parte que modifica la base de datos, creo que tiene ver con la funcion que toca el POST, posiblemente haya que cambiar la funcion que modifica los datos a la funcion de alumno.

Una vez que funcione hace el pull request

**Comment by mcolombo87** [comment]
El problema es que jamás va a la función, llama por URL a Alumno, al hacer el POST lo envia a la misma funcion del Views, nunca llega a "editar_datos".  Elimina la función y mete todo su contenido dentro de alumno (después elimina la entrada del URL). O bien busca otra manera, pero ese es el problema por el que no actualiza. Después como dijo Meior, pull request.

**Comment by Atixx** [comment]
lo soluciona #38
