### ISSUE TITLE
Datos utiles

### ISSUE THREAD

**Issue by mcolombo87** [Atixx/PlanCarrera#14]
Información de la carrera a nivel general.
Por ejemplo, links a la página oficial de la UNLa, al blog, profesores, blablabla.

**Comment by mcolombo87** [comment]
Queda abierto por cualquier idea que se ocurra agregar, se comenta aca

**Comment by Atixx** [comment]
Cerramos #22 porque tiene que ver con este Issue.
Aca seria el lugar para agregar cualquier idea informativa

**Comment by IrioneAraceli** [comment]
Por lo pronto quedaría cerrado a menos que se quiera agregar algo más.
