### ISSUE TITLE
Opinion de disenio de arbol de materia

### ISSUE THREAD

**Issue by Atixx** [Atixx/PlanCarrera#20]
![muestraarbol](https://cloud.githubusercontent.com/assets/5282820/4968298/13551e86-683b-11e4-95a8-50a31a09dddc.png)

La muestra es estatica por ahora, y lo estoy modificando para que refleje cada materia segun su estado del alumno, no entre en la parte de planificacion (click dinamico)

blanco seria no es posible anotarse
azul es posible anotarse
el resto de los colores siguie la logica de la barra de progreso (rojo en curso, amarillo aprobada, verde finalizada)

es un poco complicado modificar la ubicacion de cada materia, pero como ven se puede poner debajo de la que sea necesaria, etc..

<h4>Aca esta la pregunta importante:</h4>
<b><em>Tienen alguna propuesta para como modificar la ubicacion de cada correlativa?</b></em>

hacemos cada columna una 'catedra' o todo tirado y listo?

**Comment by mcolombo87** [comment]
El árbol queda pendiente al final de las tareas. Espero que lo podamos retomar.
