### ISSUE TITLE
Ingreso de Examenes - Problemas de Input en fecha.

### ISSUE THREAD

**Issue by mcolombo87** [Atixx/PlanCarrera#27]
Al intentar cargar un examen, no importa el formato que se use para ingresar una fecha, siempre se rechaza. Verificar, el problema puede venir de la conversión de string a date.

 Solucionar la conversión o bien agregar un componente en el template que directamente envíe el input en formato Fecha. No se ingresan los examenes a la base.

**Comment by Atixx** [comment]
hay que ver si se puede recrear
