### ISSUE TITLE
Recuperar Contraseña

### ISSUE THREAD

**Issue by mcolombo87** [Atixx/PlanCarrera#30]
Actualmente no hay método implementado. Ingeniar una idea sencilla e implementarla.

**Comment by Atixx** [comment]
Toma en cuenta que Django tiene una función para reestablecerla

**Comment by mcolombo87** [comment]
Seguramente, aún así hay que implementarla, la interfaz desde donde se va a recuperar, el acceso a ella, etc.

**Comment by mcolombo87** [comment]
Listo, falta test. No use la APP de django, todo el mecanismo lo arme yo, queria hacerlo mas allá de lo practico que podria haber sido instalar la app de django (cosa que no se porque ni leí el manual jaja)

**Comment by Atixx** [comment]
Grande maxi!!
