### ISSUE TITLE
Detalle e Info x materia.

### ISSUE THREAD

**Issue by mcolombo87** [Atixx/PlanCarrera#31]
Debe haber información sobre cada una de las materias, alcance de la misma, temario, etc.

Mínimo debe tener una descripción aunque sea corta. Lo mejor tal vez sea implementarlo en el listado de materias, queda a evaluación.

**Comment by sebastian-bascu** [comment]
Descripcion: link a la pagina especifica de la materia(en la pagina hay informacion adicional, sobre cosas no descriptas en el modal,tales como objetivos, programa y material relacionado). 
implementado en el modal de cada materia del listado de las mismas.

En caso de cumplirse todas las condiciones, muestra: Estado, Profesor, Correlativas, "Acerca de la Materia"(link) y listado de parciales con su detalle.

Creo que tiene lo indispensable, agregar mas cosas seria prescindible.

Queda abierto para revision y discusion

**Comment by Atixx** [comment]
esto es lo que cierra #37 ?
