### ISSUE TITLE
Invalidar registro si el correo existe

### ISSUE THREAD

**Issue by mcolombo87** [Atixx/PlanCarrera#34]
Al hacer la recuperación de contraseña note que (ademas de que los yankies me tienen podrido ante su falta de contemplación con la letra Ñ), que hasta ahora diferentes usuarios podian tener el mismo correo... Como regla de negocio vamos a definir que eso no es posible (al menos por ahora). 

![captura de pantalla de 2015-04-19 12 05 00](https://cloud.githubusercontent.com/assets/8608635/7219943/f0ab12c0-e68c-11e4-90c6-ee5a4d60f3c1.png)

**Comment by mcolombo87** [comment]
Va mas que nada a modo de documentación el IYU, en un rato implemento la correción dentro de esta misma rama.

**Comment by Atixx** [comment]
jajaj dale! cambia el modelo

**Comment by mcolombo87** [comment]
Listo.
