### ISSUE TITLE
Puliendo el Login

### ISSUE THREAD

**Issue by Atixx** [Atixx/PlanCarrera#5]
<h3>Mejora del login:</h3>
<p.Pasos que faltarian para mejorar el login:
<ul>
    <li>Pantalla de exito una ves registrado</li>
    <li>Posible verificacion por e-mail</li>
    <li>Redireccionamiento a la pagina home con usuario logeado</li>
    <li>Cualquier otra idea que se les ocurra</li>
</p>

**Comment by mcolombo87** [comment]
Esto ya esta, si después se implemeneta el recuperar contraseña con el correo se verá de implementar un método de verificación... mientra tanto...

**Comment by Atixx** [comment]
Ya esta en master o alguna rama? si no hace un pull request de esta y tambien de #15
